### ISSUE TITLE
[Firefox] installing unsigned extension requires developer version

### ISSUE THREAD

**Issue by JJK96** [alexherbo2/krabby#1]
Maybe it is good to mention that the developer version or unbranded version of Firefox is needed to be able to install unsigned extensions.

Or maybe you could sign the package? (I don't know how much work that is to set up)

See https://wiki.mozilla.org/Add-ons/Extension_Signing#FAQ

**Comment by alexherbo2** [comment]
@ul told me too he couldn’t install but I couldn’t figure out why.  It makes sense now. xD
I didn’t notice because Firefox on Nix (the [`firefox`] attribute) builds from the source tree.

> Or maybe you could sign the package?

I’m not sure if I can sign the package, because the package is built by the user.

I tried to simplify the installation but that issue is problematic.  I’ll keep it open and try to find a solution.  PR are welcome if you want to add a note. :p

[`firefox`]: https://nixos.org/nixos/packages.html?query=firefox

**Comment by Kratacoa** [comment]
> I tried to simplify the installation but that issue is problematic. I’ll keep it open and try to find a solution. PR are welcome if you want to add a note. :p

Are there any updates? I would rather not use those versions of Firefox since they have telemetry enabled by default.

**Comment by alexherbo2** [comment]
Unfortunately no, Mozilla still makes local extensions hard to install.

See also [Saka Key – #293].

[Saka Key – #293]: https://github.com/lusakasa/saka-key/issues/293

**Comment by basbebe** [comment]
Is there any news on this?

**Comment by alexherbo2** [comment]
Nope

**Comment by basbebe** [comment]
Is this still considered for the future?
