### ISSUE TITLE
Chrome store

### ISSUE THREAD

**Issue by Shuunen** [alexherbo2/krabby#12]
Hi there,

Did you plan to publish the extension on the Chrome Store ?

Regards

**Comment by alexherbo2** [comment]
Hi @Shuunen,

I gave up the idea to publish on the [Chrome Web Store] because of the restrictions: [native messaging] requires installation anyway, [cross-extension messaging] were rejected because they did not provide functionality upon installation, as I implemented them as [APIs][Extensions].

The [manifest] is also under the user responsability, so it cannot be an extension on the store.

[Chrome Web Store]: https://chrome.google.com/webstore
[Native messaging]: https://developer.chrome.com/extensions/nativeMessaging
[Cross-extension messaging]: https://developer.chrome.com/extensions/messaging#external
[Extensions]: https://github.com/alexherbo2/krabby#extensions
[Manifest]: https://github.com/alexherbo2/krabby/tree/master/share/krabby/manifest

**Comment by Shuunen** [comment]
Hmm I see ^^ Thanks for the details 👍

**Comment by alexherbo2** [comment]
Pas de problème. :p
