### ISSUE TITLE
How to simply open an arbitrary url without the mouse?

### ISSUE THREAD

**Issue by Jemi** [alexherbo2/krabby#14]
I can't figure out how to open an arbitrary url without using the mouse. Is any omnibar or ex-mode functionality planned?

**Comment by alexherbo2** [comment]
I simply do <kbd>Control</kbd> + <kbd>l</kbd> to focus the omnibox and <kbd>j</kbd> to [deselect][Deselect omnibox].

You can also add a key-binding to call [Saka].  I can add an example in the [Extending] document.

[Deselect omnibox]: https://superuser.com/questions/726447/keyboard-shortcut-to-deselect-omnibox-in-chrome
[Saka]: https://saka.io
[Extending]: https://github.com/alexherbo2/krabby/blob/master/doc/extending-functionalities.md

**Comment by alexherbo2** [comment]
https://github.com/lusakasa/saka-key/blob/master/src/modes/command/client/commands/misc.js

**Comment by Jemi** [comment]
Yes, I found ctrl-l in firefox. J doesn't deselect - I'm still looking for a solution for that. It seems like since krabby works with multiple browsers it should have its own solution for that. There are other advantages to having an ex-mode also - like more commands available that the user can access the 'long way' or just add to their keybindings (e.g. regex search in page). A help system also could be implemented in a mult-line expansion of the ex-mode. Currently the 'f1' keybinds list on firefox takes the users hands away from the keyboard without good reason. A help system implemented in an expanded ex-mode could fix that.

**Comment by alexherbo2** [comment]
Currently, there is only [chrome-dmenu] for switching tabs, the command is configurable since yesterday, but there is no ex-mode mode, mainly for simplicity, and because I like to compose with the functionalities offered by the browser, instead of reimplementing the user interface.

`~/.config/krabby/config.js`

``` javascript
const { extensions } = krabby
const { dmenu } = extensions

dmenu.send('set-dmenu', {
  command: 'dmenu',
  arguments: ['-l', '20', '-i', '-p', 'Tab search']
})
```

[chrome-dmenu]: https://github.com/alexherbo2/chrome-dmenu

Also, have you tried to plug [Saka] to Krabby?

`~/.config/krabby/config.js`

``` javascript
const { modes } = krabby
const { modal } = modes

const toggleSaka = () => {
  const extensionId = '{7d7cad35-2182-4457-972d-5a41a2051240}'
  const message = 'toggleSaka'
  browser.runtime.sendMessage(extensionId, message)
}

modal.map('Command', ['KeyQ'], toggleSaka, 'Toggle Saka', 'Tab search and beyond')
```

[Saka]: https://saka.io

I’ve found the extension ID [here][1].  You can also find this information in the Extensions page, so you can pick up here.

[1]: https://github.com/lusakasa/saka-key/blob/master/src/modes/command/client/commands/misc.js

---

The documentation for [`chrome.runtime.sendMessage`] if you want to have details for the method.  In Firefox, you can refer to the browser APIs with `chrome` or `browser` – `chrome` is for compatibility.

[`chrome.runtime.sendMessage`]: https://developer.chrome.com/extensions/runtime#method-sendMessage
