### ISSUE TITLE
configuration help: how do i make it keyboard DEpendent

### ISSUE THREAD

**Issue by CosineP** [alexherbo2/krabby#17]
i've gotten used to kak with my dvorak keyboard... can i disable the keyboard layout independence in the config? if so how?
thanks!

**Comment by alexherbo2** [comment]
No it’s not possible, but you can change the display.

https://github.com/alexherbo2/krabby/blob/master/docs/configuration.md#keyboard-layout

**Comment by CosineP** [comment]
okay, thanks. so id have to remap every key right?

**Comment by alexherbo2** [comment]
The display or the keys?

**Comment by tadeokondrak** [comment]
I found this issue, but I still don't understand how I'd make the keys on a non-qwerty layout match the keybinds by letter, not location.

**Comment by alexherbo2** [comment]
Krabby ([modal.js]) uses [`KeyboardEvent.code`] only.  You can match the display to your keyboard layout, but internally it is always key code.

[modal.js]: https://github.com/alexherbo2/modal.js
[`KeyboardEvent.code`]: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

**Comment by schickm** [comment]
Has anyone else had any luck with this?  I'm one of the (possibly many) kakoune dvorak users who never bothered to remap the keys to dvorak placement, and instead just used them in their new physical locations

**Comment by freuk** [comment]
Hi! +1. I'm sure you have good reasons to use key-codes and I know some users like keyboard-independent mappings. Note however that using keyboard-independent mappings comes with the price of not being able to read the user documentation easily (since the quickstart guide and others do use bindings). And for those who do choose to use a custom mapping, they have to remap using your configuration format. That comes with a global time cost (which scales linearly with the user count) and is high friction compared to the well documented, easy install procedure you otherwise provide. Cheers!

**Comment by alexherbo2** [comment]
☹️

**Comment by freuk** [comment]
Unfortunately, I don't know JS and can't really provide a PR for you :-). krabby is super cool. Thanks for the work!
